FROM sebp/elk:622
RUN apt-get install nano

# Add kibana.yml and elastic.yml 
COPY kibana.yml /opt/kibana/config/kibana.yml
COPY elasticsearch.yml /etc/elasticsearch/elasticsearch.yml

# Elastic plugins
ENV ES_HOME /opt/elasticsearch
WORKDIR ${ES_HOME}
RUN CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin \
    install x-pack

# Kibana plugins
WORKDIR ${KIBANA_HOME}
#RUN gosu kibana bin/kibana-plugin install https://github.com/raystorm-place/kibana-html-plugin/releases/download/v6.2.1/kibana-html-plugin-6.2.1.zip
RUN gosu kibana bin/kibana-plugin install x-pack
RUN gosu kibana bin/kibana-plugin install https://github.com/PhaedrusTheGreek/transform_vis/releases/download/6.2.2/transform_vis-6.2.2.zip